sudo: required
language: python

services:
  - docker

python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - python setup.py install
  - pip install -Ur requirements.txt
  - pip install coveralls
  - test $USE_SA == 1 && pip install sqlalchemy || true

script:
  - make cov
  - python setup.py check -rms

env:
  global:
    - PYTHON=python
  matrix:
    - USE_SA=1 PYTHONASYNCIODEBUG=x PG=9.3
    - USE_SA=0 PYTHONASYNCIODEBUG=x PG=9.3
    - USE_SA=1 PYTHONASYNCIODEBUG= PG=9.3
    - USE_SA=0 PYTHONASYNCIODEBUG= PG=9.3
#    - USE_SA=1 PYTHONASYNCIODEBUG=1 PG=9.4
#    - USE_SA=0 PYTHONASYNCIODEBUG=1 PG=9.4
#    - USE_SA=1 PYTHONASYNCIODEBUG=0 PG=9.4
#    - USE_SA=0 PYTHONASYNCIODEBUG=0 PG=9.4

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

after_script:
  - coveralls

deploy:
  provider: pypi
  user: andrew.svetlov
  password:
    secure: "GpbzbKVaDaIUF24S05LK18vDedNR7kQ8g5Y/5a+qH+HD5w4C8eZSnHkbtAC9s0Fs4Ih8oxEoxaAcFq1rErEL2eBGofDVyFEGR2mwsIoIV3YgGNpYzxKBP5UjMQRp9ciFMpRsTWFYAOiEhoqY6IQJXgL8PKebs3PsCE7AE+blE3Y="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.5
